### PR TITLE
fix #104, #105

### LINKED ISSUE #104: .size() vs .lenght
It is necessary to replace ".size()" with ".lenght"
file redactor.js
Otherwise, an error occurs

**line 6913**
`if ($current.closest(element).lenght > 0)`

**line 1463**
`if ($(e.target).closest('.redactor-editor, .redactor-toolbar, .redactor-dropdown').lenght !== 0)`

### PR DESCRIPTION
**Pull request by onmotion**
upgrade for jquery 3.2+ (since yii 2.0.13)

### CODE REVIEW

**Comment by prsolucoes** [comment]
Please, merge it.

**Comment by prsolucoes** [comment]
I think this project is abandoned and not will be merge. @onmotion, can i download from your branch inside composer?

Thanks.

**Comment by vova07** [comment]
@onmotion thanks for contribution!
@prsolucoes sorry for delay!

**Comment by prsolucoes** [comment]
After update i get a lot of errors. Is only with me?

image

**Pull request merged**
